import os
import requests
from scanner import scan
from ai_explainer import explain_ghost

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO = os.getenv("GITHUB_REPO")  # format: username/repo-name

def create_github_issue(ghost):
    ai_text = explain_ghost(ghost)
    
    # Extract fix command
    fix_cmd = ""
    if "FIX_COMMAND:" in ai_text:
        fix_cmd = ai_text.split("FIX_COMMAND:")[-1].strip().split("\n")[0].strip()
    else:
        fix_cmd = f"kcadm.sh update users/{ghost.get('user_id','<id>')} -r company-demo -s enabled=false"

    title = f"🚨 Ghost Identity Detected: {ghost['username']} [{ghost['risk_level']}]"
    
    body = f"""## Ghost Identity Alert

**Username:** `{ghost['username']}`  
**Risk Level:** {ghost['risk_level']}  
**Roles:** {', '.join(ghost['roles']) or 'none'}  
**Last Login:** {'Never' if not ghost.get('last_login') else ghost['last_login']}  

---

## Detection Reasons
{chr(10).join([f'- {r}' for r in ghost['reasons']])}

---

## AI Security Analysis
{ai_text}

---

## Remediation Command
```bash
{fix_cmd}
```

---

> ⚠️ This issue was automatically generated by Ghost Access IAM Scanner.  
> Review the findings and run the remediation command after approval.

**Labels:** `security`, `iam`, `ghost-identity`, `{ghost['risk_level'].lower()}`
"""

    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }

    # Check if issue already exists
    existing = requests.get(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        headers=headers,
        params={"state": "open", "labels": "ghost-identity"}
    ).json()

    for issue in existing:
        if ghost['username'] in issue['title']:
            print(f"  Issue already exists for {ghost['username']} — skipping")
            return

    # Create the issue
    response = requests.post(
        f"https://api.github.com/repos/{GITHUB_REPO}/issues",
        headers=headers,
        json={"title": title, "body": body, "labels": ["security", "ghost-identity", ghost['risk_level'].lower()]}
    )

    if response.status_code == 201:
        print(f"  Issue created for {ghost['username']}: {response.json()['html_url']}")
    else:
        print(f"  Failed for {ghost['username']}: {response.status_code} {response.text}")

def run():
    print("Scanning for ghosts...")
    ghosts = scan()
    print(f"Found {len(ghosts)} ghost(s)\n")
    
    critical_ghosts = [g for g in ghosts if g['risk_level'] == 'Critical']
    print(f"Creating issues for {len(critical_ghosts)} critical ghost(s)...\n")
    
    for ghost in critical_ghosts:
        create_github_issue(ghost)

if __name__ == "__main__":
    run()